version: '3.8'

services:
  react-app:
    build: 
      context: ./frontend
    stdin_open: true
    ports:
      - "3001:3001"
    networks:
      - emplyApp
    
  api-server:
    build: 
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - emplyApp
    depends_on:
      - pg

  pg:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - emplyApp
    environment:
       POSTGRES_PASSWORD: password
       POSTGRES_USER: postgres
  
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - emplyApp

networks:
  emplyApp:
    driver: bridge