version: '3'
services:
  react-app:
    image: employeeapp
    stdin_open: true
    ports:
      - "3001:3001"
    depends_on:
      - api-server
    networks:
      - emplyApp
    
  api-server:
    image: employeebackend
    ports:
      - "3000:3000"
    networks:
      - emplyApp
    depends_on:
      - pg

  pg:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - emplyApp
    environment:
       POSTGRES_PASSWORD: password
       POSTGRES_USER: postgres

networks:
  emplyApp:
    driver: bridge